server:
  port: 8080
springdoc:
  api-docs:
    path: /rp/api-docs
  swagger-ui:
    path: /rp/swagger-ui
spring:
  profiles:
    default: local-dev
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
